// <auto-generated />
using ExamenBoeriuCosmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenBoeriuCosmin.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240125131331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("ExamenBoeriuCosmin.Entities.Materie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nume")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Materii");
                });

            modelBuilder.Entity("ExamenBoeriuCosmin.Entities.Profesor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nume")
                        .HasColumnType("TEXT");

                    b.Property<string>("prenume")
                        .HasColumnType("TEXT");

                    b.Property<string>("tip")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("MaterieProfesor", b =>
                {
                    b.Property<int>("Materiiid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Profesoriid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Materiiid", "Profesoriid");

                    b.HasIndex("Profesoriid");

                    b.ToTable("MaterieProfesor");
                });

            modelBuilder.Entity("MaterieProfesor", b =>
                {
                    b.HasOne("ExamenBoeriuCosmin.Entities.Materie", null)
                        .WithMany()
                        .HasForeignKey("Materiiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamenBoeriuCosmin.Entities.Profesor", null)
                        .WithMany()
                        .HasForeignKey("Profesoriid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
